version: "2"

networks:
  default:
    driver: bridge

services:
  backend:
    build: .
    networks:
      - default
    ports:
      - "7773:7771"
    environment:
      MYSQL_HOST: "database:3306"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "handh-school"
      START_DELAY: 10s
      AUTH_USER: "admin"
      AUTH_PASSWORD: "password"
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_DATABASE: "handh-school"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
